---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: tf-xs3.aws.crossplane.afterpay.cloud
  namespace: upbound-system
  labels:
    provider: terraform
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: aws.crossplane.afterpay.cloud/v1beta1
    kind: XS3
  resources:
    - name: terraform-s3
      base:
        apiVersion: tf.upbound.io/v1beta1
        kind: Workspace
        spec:
          forProvider:
            source: Inline
            initArgs:
              - -upgrade=true
            planArgs:
              - -parallelism=2
            applyArgs:
              - -auto-approve
            module: |
              resource "aws_s3_bucket" "this" {
                bucket = var.bucket_name
                tags = {
                  name        = var.bucket_name
                  created_by  = "ops-kube-crossplane-terraform"
                  managed_by  = "crossplane terraform-provider"
                  team        = "Platform Kompute"
                }
              }

              resource "aws_s3_bucket_acl" "this" {
                bucket = aws_s3_bucket.this.id
                acl    = "private"
                depends_on = [aws_s3_bucket_ownership_controls.this]
              }

              resource "aws_s3_bucket_ownership_controls" "this" {
                bucket = aws_s3_bucket.this.id
                rule {
                  object_ownership = "BucketOwnerPreferred"
                }
              }

              variable "bucket_name" {
                description = "bucket name"
                type        = string
              }

              output "bucket_id" {
                value       = aws_s3_bucket.this.id
                description = "Bucket ARN"
              }
            vars:
              - key: bucket_name
          providerConfigRef:
            name: crossplane-provider-terraform-conf-v1   
      patches:
        - fromFieldPath: spec.bucket_name
          toFieldPath: spec.forProvider.vars[0].value
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.outputs.bucket_id
          toFieldPath: status.outputs.bucket_id
          policy:
            fromFieldPath: Optional