---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: tf-xs3.aws.crossplane.afterpay.cloud
  namespace: upbound-system
  labels:
    provider: terraform
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: aws.crossplane.afterpay.cloud/v1beta1
    kind: XS3
  patchSets:
    - name: common
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: spec.writeConnectionSecretToRef.name
        - fromFieldPath: metadata.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
  resources:
    - name: terraform-s3
      base:
        apiVersion: tf.upbound.io/v1beta1
        kind: Workspace
        spec:
          forProvider:
            source: Inline
            module: |
              resource "aws_s3_bucket" "crossplane_composition_s3" {
                bucket = var.bucket_name
                tags = {
                  Name        = var.bucket_name
                  CreatedBy   = "crossplane terraform-provider"
                }
              }

              resource "aws_s3_bucket_acl" "crossplane_composition_s3" {
                bucket = aws_s3_bucket.crossplane_composition_s3.id
                acl    = "private"
              }

              variable "bucket_name" {
                description = "bucket name"
                type        = string
              }

              output "bucket_id" {
                value       = aws_s3_bucket.crossplane_composition_s3.id
                description = "Bucket ARN"
              }
            vars:
              - key: bucket_name
            providerConfigRef:
              name: crossplane-provider-terraform-conf-v1

      patches:
        - type: PatchSet
          patchSetName: common
        - fromFieldPath: spec.bucket_name
          toFieldPath: spec.forProvider.vars[0].value
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.outputs.bucket_id
          toFieldPath: status.outputs.bucket_id
          policy:
            fromFieldPath: Optional