---
apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: crossplane-terraform-s3
spec:
  forProvider:
    source: Inline
    initArgs:
      - -upgrade=true
    applyArgs:
      - -auto-approve
    module: |
      resource "aws_s3_bucket" "terraform-s3" {
        bucket = "crossplane-terraform-s3-<< .config.clusterName >>"
      }

      resource "aws_s3_bucket_acl" "terraform-s3" {
        bucket = aws_s3_bucket.terraform-s3.id
        acl    = "private"
      }
  writeConnectionSecretToRef:
    namespace: upbound-system
    name: crossplane-terraform-s3
  providerConfigRef:
    name: crossplane-provider-terraform-conf-v1