---
apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: workspace-<< .config.s3.name >>
  namespace: << .config.namespace >>
spec:
  forProvider:
    source: Inline
    initArgs:
      - -upgrade=true
    applyArgs:
      - -auto-approve
    module: |
      resource "aws_s3_bucket" "crossplane_terraform_s3" {
        bucket = var.bucket_name
        tags = {
          name        = var.bucket_name
          created_by  = "ops-kube-crossplane-terraform"
          managed_by  = "crossplane terraform-provider"
          team        = "Platform Kompute"
        }
      }

      resource "aws_s3_bucket_acl" "crossplane_terraform_s3" {
        bucket = aws_s3_bucket.crossplane_terraform_s3.id
        acl    = "private"
      }

      variable "bucket_name" {
        description = "bucket name"
        type        = string
      }

      output "bucket_id" {
        value       = aws_s3_bucket.crossplane_terraform_s3.id
        description = "Bucket ARN"
      }
    vars:
      - key: bucket_name
        value: "crossplane-terraform-s3-<< .config.clusterName >>"
  writeConnectionSecretToRef:
    namespace: << .config.namespace >>
    name: workspace-<< .config.s3.name >>
  providerConfigRef:
    name: crossplane-provider-terraform-conf-v1