---
apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: crossplane-terraform-s3
  namespace: upbound-system
spec:
  forProvider:
    source: Inline
    initArgs:
      - -upgrade=true
    applyArgs:
      - -auto-approve
    module: |
      resource "aws_s3_bucket" "crossplane_terraform_s3" {
        bucket = var.bucket_name
        tags = {
          Name        = var.bucket_name
          CreatedBy   = "crossplane terraform-provider"
        }
      }

      resource "aws_s3_bucket_acl" "crossplane_terraform_s3" {
        bucket = aws_s3_bucket.crossplane_terraform_s3.id
        acl    = "private"
      }

      variable "bucket_name" {
        description = "bucket name"
        type        = string
      }

      output "bucket_id" {
        value       = aws_s3_bucket.crossplane_terraform_s3.id
        description = "Bucket ARN"
      }

    vars:
      - key: bucket_name
        value: "crossplane-terraform-s3-<< .config.clusterName >>"
  
  writeConnectionSecretToRef:
    namespace: upbound-system
    name: crossplane-terraform-s3
  providerConfigRef:
    name: crossplane-provider-terraform-conf-v1