---
AWSTemplateFormatVersion: 2010-09-09
Description: eks cluster crossplane terraform-provider access permission
Resources:

  Role:
    Type: AWS::IAM::Role
    Properties:
      PermissionsBoundary: !Sub arn:aws:iam::${AWS::AccountId}:policy/ap-service-boundary
      RoleName: kube-crossplane-terraform-provider-<< .config.clusterName >>
      Path: /k8s/<< .config.clusterName >>/
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/oidc.eks.${AWS::Region}.amazonaws.com/id/<< .config.clusterId >>
            Action: sts:AssumeRoleWithWebIdentity

      Policies:
        - PolicyName: ops-kube-crossplane-terraform-provider
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: "Allow"
              Action:
                - "iam:Generate*"
                - "iam:Get*"
                - "iam:List*"
                - "iam:Simulate*"
                - "iam:TagRole"
                - "iam:UntagRole"
                - "iam:TagUser"
                - "iam:UntagUser"
                - "iam:TagInstanceProfile"
                - "iam:UntagInstanceProfile"
                - "iam:AttachRolePolicy"
                - "iam:CreatePolicy"
                - "iam:CreatePolicyVersion"
                - "iam:CreateRole"
                - "iam:DeletePolicyVersion"
                - "iam:DeleteRole"
                - "iam:DeleteRolePolicy"
                - "iam:DetachRolePolicy"
                - "iam:PassRole"
                - "iam:PutRolePermissionsBoundary"
                - "iam:PutRolePolicy"
                - "iam:SetDefaultPolicyVersion"
                - "s3:*"
                - "dynamodb:*"
                - "ec2:*"
                - "rds:*"
                - "backup:*"
                - "backup-storage:*"
              Resource:
                - "*"