---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdynamodb.aws.crossplane.afterpay.cloud
spec:
  group: aws.crossplane.afterpay.cloud
  names:
    kind: XDynamodb
    plural: xdynamodb
  claimNames:
    kind: Dynamodb
    plural: dynamodb
  versions:
  - name: v1beta1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              hash_key: 
                type: string  
              range_key: 
                type: string
              global_secondary_indexes: 
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              local_secondary_indexes:
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              replica_regions:
                type: array
                items:
                  type: string
              attributes:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    type:
                      type: string
              resourceConfig:
                type: object
                properties:
                  providerConfigRef:
                    type: string
          status:
            description: Status defines the observed state of Terraform
            type: object
            x-kubernetes-preserve-unknown-fields: true