# Terraform
---
apiVersion: tf.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: terraform-provider-conf
spec:
  pluginCache: false
  credentials:
  # - filename: aws-creds.ini
  #   source: Secret
  #   secretRef:
  #     namespace: crossplane-system
  #     name: aws-creds
  #     key: credentials
  - filename: .git-credentials
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: git-credentials
      key: .git-credentials
  configuration: |
      provider "aws" {
        shared_credentials_file = "aws-creds.ini"
        region = "us-west-2"
      }