---
apiVersion: pkg.crossplane.io/v1
kind: ControllerConfig
metadata:
  name: terraform-provider
  namespace: upbound-system
  labels:
    app: crossplane-provider-terraform
spec:
  args:
    - -d
    - --poll=5m
    - --max-reconcile-rate=10

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: terraform-provider
  namespace: upbound-system
  labels:
    app: crossplane-provider-terraform
spec:
  package: xpkg.upbound.io/upbound/provider-terraform:v0.6.0
  controllerConfigRef:
    name: terraform-provider
