---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xs3.aws.v1beta1.crossplane.afterpay.cloud
  labels:
    version: v1beta1
spec:
  group: aws.v1beta1.crossplane.afterpay.cloud
  names:
    kind: XS3
    plural: xs3
  claimNames:
    kind: S3
    plural: s3
  versions:
  - name: v1beta1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              bucket_name:
                type: string
            required:
              - bucket_name
          status:
            description: Status defines the observed state of Terraform
            type: object
            properties:
              outputs:
                description: Freeform field containing status information for s3
                type: object
                x-kubernetes-preserve-unknown-fields: true